### ISSUE TITLE
Gradle 3.0: Declaring custom 'clean' task when using the standard Gradle lifecycle plugins is not allowed.

### ISSUE THREAD

**Issue by holmes** [palantir/gradle-npm-run-plugin#17]
Tried using this on a gradle 3.1 build and can't get it to do anything. 

The gradle section is just applying plugins and configuring the root react folder:
```
apply plugin: 'kotlin'
apply plugin: 'war'

apply plugin: 'com.moowork.node'
apply plugin: "com.palantir.npm-run"


node {
  nodeModulesDir = file("${project.projectDir}/src/main/react")
}
```

**Output:**

```
/work/homeseer-brains holmes/react * gw clean
Parallel execution with configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'ponderosa'.
> Declaring custom 'clean' task when using the standard Gradle lifecycle plugins is not allowed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.713 secs
/work/homeseer-brains holmes/react * gw -version

------------------------------------------------------------
Gradle 3.1
------------------------------------------------------------

Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.12.3 x86_64
```

**Comment by paulwilton** [comment]
yep same here

**Comment by jmcampanini** [comment]
this plugin creates a `:clean` task for you. it's an empty task that triggers an `npm run clean`. you can see the code [here][1].

the intention is to have this applied to a project that is JUST the frontend and this plugin helps give you tasks that follow a typical java lifecycle (`:clean`, `:build`, etc.). if you just want to run `npm` commands, you can just apply the `com.moowork.node` plugin and that should let you.

does that work for your use case?

[1]: https://github.com/palantir/gradle-npm-run-plugin/blob/develop/src/main/groovy/com/palantir/npmrun/NpmRunPlugin.groovy#L36-L44

**Comment by jmcampanini** [comment]
going to close. let me know if this is still an issue
